version: '3.9'
services:
  tasks:
    env_file:
      - .env
    container_name: rock_service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres_rock
  postgres_rock:
    env_file:
      - .env
    image: postgres:latest
    container_name: rock_db
    restart: always
    ports:
      - "49781:5432"

# docker compose up -d